### ISSUE TITLE
Edupage logging out after some time

### ISSUE THREAD

**Issue by cfpwastaken** [loumadev/EdupageAPI#13]
```
#
# A fatal error has occurred!
#
# This is probably not your fault!
# If this happens often, please consider reporting a bug.
#
# Error thrown:
#  ParseError: Failed to parse timetable data from html
#      at Function.parse (/media/cfp/Volume/Projects/edupageCLI/node_modules/edupage-api/src/Timetable.js:70:51)
#      at Edupage.fetchTimetablesForDates (/media/cfp/Volume/Projects/edupageCLI/node_modules/edupage-api/src/Edupage.js:466:27)
#      at processTicksAndRejections (node:internal/process/task_queues:96:5)
#      at async Edupage.getTimetableForDate (/media/cfp/Volume/Projects/edupageCLI/node_modules/edupage-api/src/Edupage.js:426:11)
#      at async timetable (/media/cfp/Volume/Projects/edupageCLI/main.js:36:30)
#      at async /media/cfp/Volume/Projects/edupageCLI/main.js:178:7
#
# Summary:
#  Time: Fri Jan 21 2022 17:21:57 GMT+0100 (Central European Standard Time)
#  EdupageAPI version: v0.7.14
#  Node.js version: v16.13.0
#  Error log: /media/cfp/Volume/Projects/edupageCLI/node_modules/edupage-api/logs/fatal_error_2022-01-21T16-21-57Z.json
#
# If you would like to submit an issue, please visit:
#  > https://github.com/loumadev/EdupageAPI/issues
#  (Please, include this error message + error log)
#
```

✖ Error!!
```
TypeError: Cannot read properties of undefined (reading 'dates')
    at Edupage.fetchTimetablesForDates (/media/cfp/Volume/Projects/edupageCLI/node_modules/edupage-api/src/Edupage.js:467:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Edupage.getTimetableForDate (/media/cfp/Volume/Projects/edupageCLI/node_modules/edupage-api/src/Edupage.js:426:11)
    at async timetable (/media/cfp/Volume/Projects/edupageCLI/main.js:36:30)
    at async /media/cfp/Volume/Projects/edupageCLI/main.js:178:7
```

Error log:
```json
{
	"error": {
		"stack": "ParseError: Failed to parse timetable data from html\n    at Function.parse (/media/cfp/Volume/Projects/edupageCLI/node_modules/edupage-api/src/Timetable.js:70:51)\n    at Edupage.fetchTimetablesForDates (/media/cfp/Volume/Projects/edupageCLI/node_modules/edupage-api/src/Edupage.js:466:27)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Edupage.getTimetableForDate (/media/cfp/Volume/Projects/edupageCLI/node_modules/edupage-api/src/Edupage.js:426:11)\n    at async timetable (/media/cfp/Volume/Projects/edupageCLI/main.js:36:30)\n    at async /media/cfp/Volume/Projects/edupageCLI/main.js:178:7",
		"message": "Failed to parse timetable data from html",
		"name": "ParseError"
	},
	"data": {
		"html": "JS: /* Error6511024354099 */ ASC.reloadPage();",
		"match": null
	}
}
```

Stuff that may be causing the problem:
I left the program running for a very long time, maybe it logged out after some time and thats why?

**Comment by loumadev** [comment]
Have you been calling any methods during that long period? Edupage should extend your current session when you send a request. I could implement some mechanisms to automatically send some ping request repeatedly in some period to keep the session.

**Comment by cfpwastaken** [comment]
Nope, it was not doing anything in that time.

**Comment by ivanhrabcak** [comment]
There is the same issue in the python edupage-api, so this is probably a bigger issue - maybe there need to be additional requests to extend the session (portalPing?).

**Comment by cfpwastaken** [comment]
yes this is an issue with python edupage-api, js edupageapi, and most likely cdupage too.

**Comment by ivanhrabcak** [comment]
Nice! Did the new update solve your issue?

Edit: Look at the next comment for more info

**Comment by loumadev** [comment]
I just publish 2 new releases with session pinging added. In case of some failure, there's also a second release which tries to resolve those issues automatically. Hopefully, this will solve your issue.

**Comment by ivanhrabcak** [comment]
Is this and #12 resolved?

**Comment by loumadev** [comment]
Probably not, there's big update planned, but currently, I have no enough time to work on it. I think, I might be able to migrate all this html parsing stuff to mobile api in like one or two weeks. Hopefully then it will be much more stable.

**Comment by cfpwastaken** [comment]
Gonna leave it running in the background now.

**Comment by cfpwastaken** [comment]
Ubuntu crashed. Guess this is not happening today

**Comment by cfpwastaken** [comment]
I think i can consider this to be fixed now. If it happens again I will reopen this issue.

**Comment by cfpwastaken** [comment]
The fix seems to be not working.

**Comment by cfpwastaken** [comment]
My server is logging out after some time too! It has the latest version of edupageapi and has its own edupage.refresh() on intervals too!

**Comment by cfpwastaken** [comment]
A way to fix this could be an option to automatically log back in with the provided credentials if it cant connect anymore.
