### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by ivanhrabcak** [loumadev/EdupageAPI#14]
Hello, I've encountered a problem which I think was unavoidable (I've mentioned previously that it is a problem, but it was dismissed).

I cannot login with my credentials. They are correct, but in my school, I can't login with `portal.edupage.org`, only with `subdomain.edupage.org` where `subdomain` is the subdomain of my school. That is why your login method does not work with my credentials.

__Error__:
```
#
# A fatal error has occurred!
#
# This is probably not your fault!
# If this happens often, please consider reporting a bug.
#
# Error thrown:
#  EdupageError: Edupage server did not redirect login request to proper origin
#      at /home/ivanhrabcak/PythonProjects/edupog-backend/node_modules/edupage-api/src/User.js:221:52
#      at processTicksAndRejections (node:internal/process/task_queues:96:5)
#
# Summary:
#  Time: Fri Jan 28 2022 15:44:52 GMT+0100 (Central European Standard Time)
#  EdupageAPI version: v0.8.1
#  Node.js version: v17.4.0
#  Error log: /home/ivanhrabcak/PythonProjects/edupog-backend/node_modules/edupage-api/logs/fatal_error_2022-01-28T14-44-52Z.json
#
# If you would like to submit an issue, please visit:
#  > https://github.com/loumadev/EdupageAPI/issues
#  (Please, include this error message + error log)
#
```

__Error Log__:
```json
	"error": {
		"stack": "EdupageError: Edupage server did not redirect login request to proper origin\n    at /home/ivanhrabcak/PythonProjects/edupog-backend/node_modules/edupage-api/src/User.js:221:52\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
		"message": "Edupage server did not redirect login request to proper origin",
		"name": "EdupageError"
	},
	"data": {
		"html": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\"><html><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=utf-8\"><title> EduPage </title><style>html, body {margin: 0px;padding: 0px;height: 100%;}body,td,input,select { font-family: Verdana; \tfont-size: 10pt;\tcolor: #1f497d;}th {font-family: Verdana; font-size: 10pt; color: #FFFFFF; background-color: #4B6BAC}tr.sedeth th {\tbackground-color: #333333;}tr.zeleneth th {\tbackground-color: #1c611c;}tr.table_row1 {\tbackground-color: #E9F7FF; }tr.table_row2 {\tbackground-color: #D3E8FC; }tr.table_row1_sede {background-color: #dddddd; }tr.table_row2_sede {background-color: #ededed;}tr.table_row1_sede td {color:#222222}tr.table_row2_sede td {color:#222222}tr.table_row1_zelene {background-color: #e3f7b8; }tr.table_row2_zelene {background-color: #d7efa5;}tr.table_row1_zelene td {color:#164c16}tr.table_row2_zelene td {color:#164c16}td.td_border { border: solid 1px #D3E8FC; }img {\tborder:none;}a {\ttext-decoration: none;\t\tcolor: #1f497d;}a:hover{\ttext-decoration: underline;}a.th{\tcolor: #FFFFFF;}@media print {\thtml, body {\t\tmargin: 0px;\t\tpadding: 0px;\t\theight: 100%;\t}\tbody,td,input,select { font-family: Verdana; \t\tfont-size: 12pt;\t\tcolor: #000000;\t}\tth {\t\tfont-family: Verdana; font-size: 12pt; color: #000000; font-weight:bold;\t}\t\ttr.sedeth th {\t\tbackground-color: #333333;\t}\ttr.zeleneth th {\t\tbackground-color: #1c611c;\t}\ttr.table_row1 { }\ttr.table_row2 { }\ttr.table_row1_sede { }\ttr.table_row2_sede {}\ttr.table_row1_sede td {}\ttr.table_row2_sede td {}\t\ttr.table_row1_zelene {}\ttr.table_row2_zelene {}\ttr.table_row1_zelene td {}\ttr.table_row2_zelene td {}\t\ttable.printBorder td {border: 1px solid #000000;}\ttable.printBorder th {border: 1px solid #000000;}\ttable.printBorder {border-collapse: collapse;border:1px solid #000000;}\t\timg {\t\tborder:none;\t}\ta {\t\ttext-decoration: none;\t\t\t\tcolor: #000000;\t}\t\ta:hover{\t\ttext-decoration: underline;\t}\t\t\ta.th{\t\tcolor: #000000;\t}</style><link rel=\"stylesheet\" type=\"text/css\" href=\"/global/pics/css/jquery-ui-1.10.2.css\" />\t\t\t\t\t\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/global/pics/css/edubar.css?v=20140415\" />\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\" src=\"/global/pics/js/jquery/jquery-1.9.1.min.js?v=20130325\"></script>\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\" src=\"/global/pics/js/jquery/jquery-ui-1.10.2.min.js\"></script>\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\" src=\"/langs/pics/js/lang_sk.js\"></script>\t\t\t\t\t<script src=\"/global/pics/js/edubarUtils.js?v=20140415\" type=\"text/javascript\"></script>\t\t\t\t\t</HEAD><body style=\"margin:0px;overflow:visible;\">Stránka sa načítava...<script language=\"javascript\">window.open(\"https://portal.edupage.org/?login&PSID=REDACTED\", \"_top\");</script></body></html>",
		"url": "https://portal.edupage.org/?login&PSID=REDACTED",
		"origin": "portal",
		"ESID": "REDACTED"
	}
```

I encounter the same problem when using the `login_auto` function in the develop branch of [edupage-api](https://github.com/ivanhrabcak/edupage-api) with my credentials - `login_auto` uses the same login method as you.
```python
from edupage_api import Edupage
edupage = Edupage()
edupage.login_auto(username, password)
"""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ivanhrabcak/PythonProjects/edupog-backend/edupog/edupage_api/__init__.py", line 31, in login_auto
    Login(self).login_auto(username, password)
  File "/home/ivanhrabcak/PythonProjects/edupog-backend/edupog/edupage_api/login.py", line 34, in login_auto
    self.__parse_login_data(data)
  File "/home/ivanhrabcak/PythonProjects/edupog-backend/edupog/edupage_api/login.py", line 7, in __parse_login_data
    json_string = data.split("$j(document).ready(function() {")[1] \
IndexError: list index out of range
"""
```

But when using `login` (you also have to provide your school's subdomain), everythings runs ok.
![image](https://user-images.githubusercontent.com/39710116/151568813-ac012834-1fd6-4448-95a1-1c7ec934813c.png)

This issue is related to [#6 in eduage-api](https://github.com/ivanhrabcak/edupage-api/issues/6),  #5 and the fix is described [here](https://github.com/loumadev/EdupageAPI/issues/2#issuecomment-921246010)

**Comment by ivanhrabcak** [comment]
The issue is solved when logging in with the `MobileAPI` branch (now there's another unrelated problem, but in our private conversation we've talked about it, so there's no need to keep this issue open).
