### ISSUE TITLE
Failed to init the Grade object warning (from #4)

### ISSUE THREAD

**Issue by ghost** [loumadev/EdupageAPI#6]
This is the crash log (#4):

```
An error has occurred!

This is probably not your fault!
It should not cause the program to crash, but some functionality can be limited.
If this happens often, please consider reporting a bug.
You can disable the warnings by including "--edu-disable-warnings=true" as a CLI argument.

Error thrown:
  EdupageError: Failed to init the Grade object: Cannot find provider
      at Grade.init (C:\Users\dajzr\OneDrive\Počítač\node_modules\edupage-api\src\Grade.js:199:48)
      at new Grade (C:\Users\dajzr\OneDrive\Počítač\node_modules\edupage-api\src\Grade.js:177:41)
      at C:\Users\dajzr\OneDrive\Počítač\node_modules\edupage-api\src\Edupage.js:334:89
      at Array.map (<anonymous>)
      at Edupage._updateInternalValues (C:\Users\dajzr\OneDrive\Počítač\node_modules\edupage-api\src\Edupage.js:334:77)
      at Edupage.refresh (C:\Users\dajzr\OneDrive\Počítač\node_modules\edupage-api\src\Edupage.js:194:8)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async C:\Users\dajzr\OneDrive\Počítač\node_modules\edupage-api\src\Edupage.js:169:5

Summary:
  Time: Fri Sep 17 2021 15:46:54 GMT+0200 (Central European Summer Time)
  EdupageAPI version: v0.7.9
  Node.js version: v16.9.1
  Error log: C:\Users\dajzr\OneDrive\Počítač\node_modules\edupage-api\logs\warning_2021-09-17T13-46-54Z.json

If you would like to submit an issue, please visit:
  > https://github.com/loumadev/EdupageAPI/issues
  (Please, include this error message + error log)
```

```javascript
{
	"error": {
		"stack": "EdupageError: Failed to init the Grade object: Cannot find provider\n    at Grade.init (C:\\Users\\dajzr\\OneDrive\\Počítač\\node_modules\\edupage-api\\src\\Grade.js:199:48)\n    at new Grade (C:\\Users\\dajzr\\OneDrive\\Počítač\\node_modules\\edupage-api\\src\\Grade.js:177:41)\n    at C:\\Users\\dajzr\\OneDrive\\Počítač\\node_modules\\edupage-api\\src\\Edupage.js:334:89\n    at Array.map (<anonymous>)\n    at Edupage._updateInternalValues (C:\\Users\\dajzr\\OneDrive\\Počítač\\node_modules\\edupage-api\\src\\Edupage.js:334:77)\n    at Edupage.refreshTimeline (C:\\Users\\dajzr\\OneDrive\\Počítač\\node_modules\\edupage-api\\src\\Edupage.js:246:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Timeout._onTimeout (C:\\Users\\dajzr\\OneDrive\\Počítač\\edupage jeblina\\index.js:23:9)",
		"message": "Failed to init the Grade object: Cannot find provider",
		"name": "EdupageError"
	},
	"data": {
		"_data": {
			"provider": "agenda",
			"znamkaid": "-2",
			"studentid": "39735",
			"predmetid": "37765",
			"udalostid": "0",
			"mesiac": "V1",
			"data": "o",
			"datum": "0000-00-00 00:00:00",
			"ucitelid": "0",
			"podpisane": null,
			"podpisane_rodic": null,
			"timestamp": "2021-09-14 12:23:44",
			"stav": "o"
		}
	}
}
```

**Comment by Mareceeek** [comment]
and this is the crash log

#
# An error has occurred!
#
# This is probably not your fault!
# It should not cause the program to crash, but some functionality can be limited.
# If this happens often, please consider reporting a bug.
# You can disable the warnings by including "--edu-disable-warnings=true" as a CLI argument.
#
# Error thrown:
#  EdupageError: Failed to init the Grade object: Cannot find provider
#      at Grade.init (C:\Users\dajzr\OneDrive\Počítač\node_modules\edupage-api\src\Grade.js:199:48)
#      at new Grade (C:\Users\dajzr\OneDrive\Počítač\node_modules\edupage-api\src\Grade.js:177:41)
#      at C:\Users\dajzr\OneDrive\Počítač\node_modules\edupage-api\src\Edupage.js:334:89
#      at Array.map (<anonymous>)
#      at Edupage._updateInternalValues (C:\Users\dajzr\OneDrive\Počítač\node_modules\edupage-api\src\Edupage.js:334:77)
#      at Edupage.refresh (C:\Users\dajzr\OneDrive\Počítač\node_modules\edupage-api\src\Edupage.js:194:8)
#      at processTicksAndRejections (node:internal/process/task_queues:96:5)
#      at async C:\Users\dajzr\OneDrive\Počítač\node_modules\edupage-api\src\Edupage.js:169:5
#
# Summary:
#  Time: Fri Sep 17 2021 15:46:54 GMT+0200 (Central European Summer Time)
#  EdupageAPI version: v0.7.9
#  Node.js version: v16.9.1
#  Error log: C:\Users\dajzr\OneDrive\Počítač\node_modules\edupage-api\logs\warning_2021-09-17T13-46-54Z.json
#
# If you would like to submit an issue, please visit:
#  > https://github.com/loumadev/EdupageAPI/issues
#  (Please, include this error message + error log)
#

```javascript
{
	"error": {
		"stack": "EdupageError: Failed to init the Grade object: Cannot find provider\n    at Grade.init (C:\\Users\\dajzr\\OneDrive\\Počítač\\node_modules\\edupage-api\\src\\Grade.js:199:48)\n    at new Grade (C:\\Users\\dajzr\\OneDrive\\Počítač\\node_modules\\edupage-api\\src\\Grade.js:177:41)\n    at C:\\Users\\dajzr\\OneDrive\\Počítač\\node_modules\\edupage-api\\src\\Edupage.js:334:89\n    at Array.map (<anonymous>)\n    at Edupage._updateInternalValues (C:\\Users\\dajzr\\OneDrive\\Počítač\\node_modules\\edupage-api\\src\\Edupage.js:334:77)\n    at Edupage.refreshTimeline (C:\\Users\\dajzr\\OneDrive\\Počítač\\node_modules\\edupage-api\\src\\Edupage.js:246:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Timeout._onTimeout (C:\\Users\\dajzr\\OneDrive\\Počítač\\edupage jeblina\\index.js:23:9)",
		"message": "Failed to init the Grade object: Cannot find provider",
		"name": "EdupageError"
	},
	"data": {
		"_data": {
			"provider": "agenda",
			"znamkaid": "-2",
			"studentid": "39735",
			"predmetid": "37765",
			"udalostid": "0",
			"mesiac": "V1",
			"data": "o",
			"datum": "0000-00-00 00:00:00",
			"ucitelid": "0",
			"podpisane": null,
			"podpisane_rodic": null,
			"timestamp": "2021-09-14 12:23:44",
			"stav": "o"
		}
	}
}
```

**Comment by loumadev** [comment]
This bug has been fixed in a [new version](https://github.com/loumadev/EdupageAPI/releases/tag/v0.7.10), please update your package. In case of any other problems, feel free to open a new issue. (Hopefully, this update fix all your errors.)

**Comment by ghost** [comment]
okay
