### ISSUE TITLE
Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by ghost** [loumadev/EdupageAPI#7]

**Comment by loumadev** [comment]
This [line](https://github.com/loumadev/EdupageAPI/blob/master/src/Grade.js#L198) currently looks differently. Try running `npm uninstall edupage-api` and then `npm install edupage-api`.

**Comment by Mareceeek** [comment]
it is working now thank you very much!

**Comment by Mareceeek** [comment]
it crashed when someone send me message

```javascript
[
  Message {
    edupage: Edupage {
      user: [Student],
      seasons: [Array],
      students: [Array],
      teachers: [Array],
      classes: [Array],
      classrooms: [],
      parents: [Array],
      subjects: [Array],
      periods: [Array],
      timetables: [Array],
      timelineItems: [Array],
      timeline: [Array],
      plans: [Array],
      assignments: [],
      homeworks: [],
      tests: [],
      applications: [Array],
      ASC: [ASC],
      year: 2021,
      baseUrl: 'https://zsmana.edupage.org',
      grades: [Array]
    },
    id: '122341',
    type: 'sprava',
    creationDate: 2021-09-17T17:52:15.000Z,
    timelineDate: 2021-09-17T17:52:15.000Z,
    otherId: null,
    repliesCount: 0,
    lastReplyDate: null,
    isRemoved: false,
    isReply: false,
    isImportant: false,
    seenDate: 2021-09-17T17:52:15.000Z,
    isSeen: true,
    likedDate: null,
    isLiked: false,
    doneDate: null,
    isDone: false,
    isStarred: false,
    likes: 0,
    text: 'Abeceda zedla dedla',
    title: 'Marek Karol',
    participantsCount: null,
    participants: [],
    likedBy: [],
    seenBy: [],
    owner: Student {
      edupage: [Edupage],
      dateFrom: 2014-09-01T00:00:00.000Z,
      dateTo: null,
      firstname: 'Matúš',
      lastname: 'Belenčík',
      gender: 'M',
      id: '39734',
      userString: 'Student39734',
      isOut: false,
      origin: 'zsmana',
      credentials: null,
      cookies: null,
      isLoggedIn: false,
      email: null,
      number: 0,
      numberInClass: 1,
      parent1Id: '-595',
      parent2Id: '-596',
      parent3Id: '',
      parent1: undefined,
      parent2: undefined,
      parent3: null,
      class: [Class]
    },
    recipient: Student {
      edupage: [Edupage],
      dateFrom: 2014-09-01T00:00:00.000Z,
      dateTo: null,
      firstname: 'Marek',
      lastname: 'Karol',
      gender: 'M',
      id: '39735',
      userString: 'Student39735',
      isOut: false,
      origin: 'zsmana',
      credentials: null,
      cookies: null,
      isLoggedIn: false,
      email: null,
      number: 0,
      numberInClass: 4,
      parent1Id: '-597',
      parent2Id: '-749',
      parent3Id: '',
      parent1: [Parent],
      parent2: [Parent],
      parent3: null,
      class: [Class]
    },
    recipientUserString: 'StudentOnly39735',
    isWildcardRecipient: false,
    replyOf: null,
    attachments: [],
    replies: [],
    assignment: null
  }
]
C:\Users\dajzr\OneDrive\Počítač\node_modules\discord.js\src\util\Util.js:413
    if (typeof data !== 'string') throw new error(errorMessage);
                                        ^

RangeError [MESSAGE_CONTENT_TYPE]: Message content must be a non-empty string.
    at Function.verifyString (C:\Users\dajzr\OneDrive\Počítač\node_modules\discord.js\src\util\Util.js:413:41)
    at MessagePayload.makeContent (C:\Users\dajzr\OneDrive\Počítač\node_modules\discord.js\src\structures\MessagePayload.js:113:22)
    at MessagePayload.resolveData (C:\Users\dajzr\OneDrive\Počítač\node_modules\discord.js\src\structures\MessagePayload.js:128:26)
    at WebhookClient.send (C:\Users\dajzr\OneDrive\Počítač\node_modules\discord.js\src\structures\Webhook.js:165:61)
    at Timeout._onTimeout (C:\Users\dajzr\OneDrive\Počítač\edupage jeblina\index.js:40:27)    
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(code)]: 'MESSAGE_CONTENT_TYPE'
}```

**Comment by Mareceeek** [comment]
do u know how to send the fetched message into discord webhook?

**Comment by loumadev** [comment]
You have this snippet:
```javascript
if(newMessages.length) {
    //Your code here...
    console.log(newMessages);
    webhookClient.send({
        content: newMessages
    });
}
```

* Variable `newMessages` is an array of [`Message`](https://github.com/loumadev/EdupageAPI#class-message) objects
* Your Error is `RangeError [MESSAGE_CONTENT_TYPE]: Message content must be a non-empty string.`

From this information, I assume the `content` field in your `send` method should be a `string`, but you are passing there an `array`. So you have to first iterate through the array and send the messages one by one. But you can't just send a whole [`Message`](https://github.com/loumadev/EdupageAPI#class-message) object, you only need a `string`.
If you look closely into [`Message`](https://github.com/loumadev/EdupageAPI#class-message) object docs, you can see there a `text` property. This property holds the textual representation of the message, and the type is a `string` as you need.

So with this in mind, you can rewrite your code like so:
```javascript
if(newMessages.length) {
    console.log(newMessages);
    
    //Iterate the `newMessages` array
    for(const message of newMessages) {
        webhookClient.send({
            content: message.text  //Access `text` property of `message` variable
        });
    }
}
```

**Comment by Mareceeek** [comment]
thanks

**Comment by loumadev** [comment]
You are welcome!
